stages:
  - build
  - deploy

build-job:
  tags: 
  - yellow1
  stage: build
  script:
  - chmod a+x ./gradlew
  - ./gradlew --no-daemon build javadoc jacocoTestReport collectStats
  - eval $(ssh-agent -t 5m -s)
  - ssh-add <(echo "$RSYNC_KEY")
  - rsync -auvz -e "ssh" build/reports/tests/ build/libs ratwell@atria.cs.odu.edu:Avocado1/
  - ssh-agent -k
  only:
      - master

  artifacts:
    # Make entire build directory available
    # for the deploy portion of the job
    paths:
      - ./build
      - ./build/libs/WebAnalysis.jar
      - ./*.json
      - ./*.txt
      - ./*.xlsx

deploy-job:
  tags:
   - yellow1
  stage: deploy
  script:

    - eval $(ssh-agent -s)
    - ssh-add <(echo "$RSYNC_KEY")

    - rsync -auvz -e "ssh" build/docs build/reports/ build/jacoco build/libs *.json ratwell@atria.cs.odu.edu:./

    - ssh-agent -k
 